---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install essential packages
  apt:
    name:
      - ufw
      - unattended-upgrades
      - python3-passlib  # Required for password hashing
    state: latest

# --- User Management ---
- name: Create SSH user with password if provided
  user:
    name: "{{ ssh_user }}"
    name: "{{ ssh_user }}"
    groups: sudo
    shell: /bin/bash
    state: present
    password: "{{ ssh_user_password | password_hash('sha512') if ssh_user_password != '' else omit }}"
    update_password: on_create

- name: Setup SSH directory
  file:
    path: "/home/{{ ssh_user }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"

- name: Deploy public key
  authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ lookup('file', ssh_public_key_path) }}"

# --- Root Password Configuration ---
- name: Change root password if specified
  user:
    name: root
    password: "{{ new_root_password | password_hash('sha512') if new_root_password != '' else omit }}"
    update_password: on_create
  when: new_root_password != ""

# --- Maintenance ---
- name: Configure automatic updates
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1"; 
      APT::Periodic::AutocleanInterval "7";

# --- SSH Hardening ---
- name: Configure SSHd
  block:
    - name: Change SSH port
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?Port"
        line: "Port {{ ssh_port }}"
        validate: /usr/sbin/sshd -t -f %s

    - name: Disable password auth in main sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"
        validate: /usr/sbin/sshd -t -f %s

    - name: Disable password auth in all cloud-init SSH config files
      find:
        paths: /etc/ssh/sshd_config.d/
        patterns: "*cloud-init.conf"
        file_type: file
      register: cloud_init_ssh_configs

    - name: Set PasswordAuthentication no in cloud-init sshd configs
      lineinfile:
        path: "{{ item.path }}"
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"
        create: no
        validate: /usr/sbin/sshd -t -f %s
      loop: "{{ cloud_init_ssh_configs.files }}"

    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin no"
        validate: /usr/sbin/sshd -t -f %s
  notify: Restart SSHd


# --- Firewall ---
- name: Configure UFW
  block:
    - name: Allow SSH port
      command: ufw allow {{ ssh_port }}/tcp

    - name: Allow HTTP
      command: ufw allow http

    - name: Allow HTTP
      command: ufw allow https

    - name: Set default policies
      command: ufw default deny incoming

    - name: Enable UFW
      command: ufw --force enable
  notify: Restart UFW
