---
- name: Check if bridge config variables file exists
  ansible.builtin.stat:
    path: "{{ (xray_path, 'bridge_vars.yaml') | path_join }}"
  register: bridge_vars_stat

- name: Load existing bridge variables
  when: bridge_vars_stat.stat.exists
  block:
    - name: Read bridge variables file
      ansible.builtin.slurp:
        src: "{{ (xray_path, 'bridge_vars.yaml') | path_join }}"
      register: bridge_vars_raw

    - name: Parse bridge variables
      ansible.builtin.set_fact:
        bridge: "{{ bridge_vars_raw.content | b64decode | from_yaml }}"

- name: Generate bridge variables on first run
  when: not bridge_vars_stat.stat.exists
  block:
    - name: Create bridge short_id
      ansible.builtin.command: openssl rand -hex 8
      register: short_id_result
      changed_when: true

    - name: Create bridge UUID
      ansible.builtin.command:
        cmd: "{{ (xray_path, 'xray') | path_join }} uuid"
      register: uuid_result
      changed_when: true

    - name: Generate bridge x25519 keys
      ansible.builtin.command:
        cmd: "{{ (xray_path, 'xray') | path_join }} x25519"
      register: x25519_result
      changed_when: true

    - name: Set bridge variables
      ansible.builtin.set_fact:
        bridge:
          uuid: "{{ uuid_result.stdout }}"
          x25519_private: "{{ x25519_result.stdout.split('\n')[0].split(': ')[1] }}"
          x25519_public: "{{ x25519_result.stdout.split('\n')[1].split(': ')[1] }}"
          short_id: "{{ short_id_result.stdout }}"

    - name: Write bridge variables file
      ansible.builtin.template:
        src: variables.yaml.j2
        dest: "{{ (xray_path, 'bridge_vars.yaml') | path_join }}"
        mode: '0644'

- name: Write Xray bridge config
  ansible.builtin.template:
    src: config.json.j2
    dest: "{{ (xray_path, 'config.json') | path_join }}"
    mode: '0644'
  notify: Restart Xray
